// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetflixStatizier.Data;

namespace NetflixStatizier.Migrations.Stats
{
    [DbContext(typeof(StatsContext))]
    [Migration("20190313071657_InitialDataDatabase")]
    partial class InitialDataDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetflixStatizier.Models.NetflixAccountModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NetflixEmail")
                        .IsRequired();

                    b.Property<string>("NetflixPassword")
                        .IsRequired();

                    b.Property<string>("NetflixProfileName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NetflixAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
