version: "3.7"
services:
    web:
        build: .
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Production"
        volumes:
            - /root/flixstats/cert:/app/letsencrypt
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Error404!"
            ACCEPT_EULA: "Y"