// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetflixStatizier.Data;

namespace NetflixStatizier.Migrations
{
    [DbContext(typeof(StatsContext))]
    [Migration("20190614121413_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetflixStatizier.Models.EntityFrameworkModels.NetflixViewedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<int>("DeviceType");

                    b.Property<int>("Duration");

                    b.Property<string>("EpisodeTitle");

                    b.Property<int>("EstRating");

                    b.Property<Guid>("Identifier");

                    b.Property<int>("Index");

                    b.Property<int>("MovieId");

                    b.Property<int>("PlaybackBookmark");

                    b.Property<DateTime>("PlaybackDateTime");

                    b.Property<string>("SeasonDescriptor");

                    b.Property<int>("SeriesId");

                    b.Property<string>("SeriesTitle");

                    b.Property<string>("Title");

                    b.Property<string>("TopNodeId");

                    b.Property<string>("VideoTitle");

                    b.HasKey("Id");

                    b.ToTable("NetflixViewedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
