using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FlixStats.Models.InputModels
{
    public class LeaderboardInputModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string CountryCode { get; set; }

        public List<SelectListItem> Countries => new List<SelectListItem>(AllCountries.OrderBy(x => x.Text));

        private List<SelectListItem> AllCountries => new List<SelectListItem>
        {
            new SelectListItem(value: "BD", text: "Bangladesh"),
            new SelectListItem(value: "BE", text: "Belgium"),
            new SelectListItem(value: "BF", text: "Burkina Faso"),
            new SelectListItem(value: "BG", text: "Bulgaria"),
            new SelectListItem(value: "BA", text: "Bosnia and Herzegovina"),
            new SelectListItem(value: "BB", text: "Barbados"),
            new SelectListItem(value: "WF", text: "Wallis and Futuna"),
            new SelectListItem(value: "BL", text: "Saint Barthelemy"),
            new SelectListItem(value: "BM", text: "Bermuda"),
            new SelectListItem(value: "BN", text: "Brunei"),
            new SelectListItem(value: "BO", text: "Bolivia"),
            new SelectListItem(value: "BH", text: "Bahrain"),
            new SelectListItem(value: "BI", text: "Burundi"),
            new SelectListItem(value: "BJ", text: "Benin"),
            new SelectListItem(value: "BT", text: "Bhutan"),
            new SelectListItem(value: "JM", text: "Jamaica"),
            new SelectListItem(value: "BV", text: "Bouvet Island"),
            new SelectListItem(value: "BW", text: "Botswana"),
            new SelectListItem(value: "WS", text: "Samoa"),
            new SelectListItem(value: "BQ", text: "Bonaire), Saint Eustatius and Saba "),
            new SelectListItem(value: "BR", text: "Brazil"),
            new SelectListItem(value: "BS", text: "Bahamas"),
            new SelectListItem(value: "JE", text: "Jersey"),
            new SelectListItem(value: "BY", text: "Belarus"),
            new SelectListItem(value: "BZ", text: "Belize"),
            new SelectListItem(value: "RU", text: "Russia"),
            new SelectListItem(value: "RW", text: "Rwanda"),
            new SelectListItem(value: "RS", text: "Serbia"),
            new SelectListItem(value: "TL", text: "East Timor"),
            new SelectListItem(value: "RE", text: "Reunion"),
            new SelectListItem(value: "TM", text: "Turkmenistan"),
            new SelectListItem(value: "TJ", text: "Tajikistan"),
            new SelectListItem(value: "RO", text: "Romania"),
            new SelectListItem(value: "TK", text: "Tokelau"),
            new SelectListItem(value: "GW", text: "Guinea-Bissau"),
            new SelectListItem(value: "GU", text: "Guam"),
            new SelectListItem(value: "GT", text: "Guatemala"),
            new SelectListItem(value: "GS", text: "South Georgia and the South Sandwich Islands"),
            new SelectListItem(value: "GR", text: "Greece"),
            new SelectListItem(value: "GQ", text: "Equatorial Guinea"),
            new SelectListItem(value: "GP", text: "Guadeloupe"),
            new SelectListItem(value: "JP", text: "Japan"),
            new SelectListItem(value: "GY", text: "Guyana"),
            new SelectListItem(value: "GG", text: "Guernsey"),
            new SelectListItem(value: "GF", text: "French Guiana"),
            new SelectListItem(value: "GE", text: "Georgia"),
            new SelectListItem(value: "GD", text: "Grenada"),
            new SelectListItem(value: "GB", text: "United Kingdom"),
            new SelectListItem(value: "GA", text: "Gabon"),
            new SelectListItem(value: "SV", text: "El Salvador"),
            new SelectListItem(value: "GN", text: "Guinea"),
            new SelectListItem(value: "GM", text: "Gambia"),
            new SelectListItem(value: "GL", text: "Greenland"),
            new SelectListItem(value: "GI", text: "Gibraltar"),
            new SelectListItem(value: "GH", text: "Ghana"),
            new SelectListItem(value: "OM", text: "Oman"),
            new SelectListItem(value: "TN", text: "Tunisia"),
            new SelectListItem(value: "JO", text: "Jordan"),
            new SelectListItem(value: "HR", text: "Croatia"),
            new SelectListItem(value: "HT", text: "Haiti"),
            new SelectListItem(value: "HU", text: "Hungary"),
            new SelectListItem(value: "HK", text: "Hong Kong"),
            new SelectListItem(value: "HN", text: "Honduras"),
            new SelectListItem(value: "HM", text: "Heard Island and McDonald Islands"),
            new SelectListItem(value: "VE", text: "Venezuela"),
            new SelectListItem(value: "PR", text: "Puerto Rico"),
            new SelectListItem(value: "PS", text: "Palestinian Territory"),
            new SelectListItem(value: "PW", text: "Palau"),
            new SelectListItem(value: "PT", text: "Portugal"),
            new SelectListItem(value: "SJ", text: "Svalbard and Jan Mayen"),
            new SelectListItem(value: "PY", text: "Paraguay"),
            new SelectListItem(value: "IQ", text: "Iraq"),
            new SelectListItem(value: "PA", text: "Panama"),
            new SelectListItem(value: "PF", text: "French Polynesia"),
            new SelectListItem(value: "PG", text: "Papua New Guinea"),
            new SelectListItem(value: "PE", text: "Peru"),
            new SelectListItem(value: "PK", text: "Pakistan"),
            new SelectListItem(value: "PH", text: "Philippines"),
            new SelectListItem(value: "PN", text: "Pitcairn"),
            new SelectListItem(value: "PL", text: "Poland"),
            new SelectListItem(value: "PM", text: "Saint Pierre and Miquelon"),
            new SelectListItem(value: "ZM", text: "Zambia"),
            new SelectListItem(value: "EH", text: "Western Sahara"),
            new SelectListItem(value: "EE", text: "Estonia"),
            new SelectListItem(value: "EG", text: "Egypt"),
            new SelectListItem(value: "ZA", text: "South Africa"),
            new SelectListItem(value: "EC", text: "Ecuador"),
            new SelectListItem(value: "IT", text: "Italy"),
            new SelectListItem(value: "VN", text: "Vietnam"),
            new SelectListItem(value: "SB", text: "Solomon Islands"),
            new SelectListItem(value: "ET", text: "Ethiopia"),
            new SelectListItem(value: "SO", text: "Somalia"),
            new SelectListItem(value: "ZW", text: "Zimbabwe"),
            new SelectListItem(value: "SA", text: "Saudi Arabia"),
            new SelectListItem(value: "ES", text: "Spain"),
            new SelectListItem(value: "ER", text: "Eritrea"),
            new SelectListItem(value: "ME", text: "Montenegro"),
            new SelectListItem(value: "MD", text: "Moldova"),
            new SelectListItem(value: "MG", text: "Madagascar"),
            new SelectListItem(value: "MF", text: "Saint Martin"),
            new SelectListItem(value: "MA", text: "Morocco"),
            new SelectListItem(value: "MC", text: "Monaco"),
            new SelectListItem(value: "UZ", text: "Uzbekistan"),
            new SelectListItem(value: "MM", text: "Myanmar"),
            new SelectListItem(value: "ML", text: "Mali"),
            new SelectListItem(value: "MO", text: "Macao"),
            new SelectListItem(value: "MN", text: "Mongolia"),
            new SelectListItem(value: "MH", text: "Marshall Islands"),
            new SelectListItem(value: "MK", text: "Macedonia"),
            new SelectListItem(value: "MU", text: "Mauritius"),
            new SelectListItem(value: "MT", text: "Malta"),
            new SelectListItem(value: "MW", text: "Malawi"),
            new SelectListItem(value: "MV", text: "Maldives"),
            new SelectListItem(value: "MQ", text: "Martinique"),
            new SelectListItem(value: "MP", text: "Northern Mariana Islands"),
            new SelectListItem(value: "MS", text: "Montserrat"),
            new SelectListItem(value: "MR", text: "Mauritania"),
            new SelectListItem(value: "IM", text: "Isle of Man"),
            new SelectListItem(value: "UG", text: "Uganda"),
            new SelectListItem(value: "TZ", text: "Tanzania"),
            new SelectListItem(value: "MY", text: "Malaysia"),
            new SelectListItem(value: "MX", text: "Mexico"),
            new SelectListItem(value: "IL", text: "Israel"),
            new SelectListItem(value: "FR", text: "France"),
            new SelectListItem(value: "IO", text: "British Indian Ocean Territory"),
            new SelectListItem(value: "SH", text: "Saint Helena"),
            new SelectListItem(value: "FI", text: "Finland"),
            new SelectListItem(value: "FJ", text: "Fiji"),
            new SelectListItem(value: "FK", text: "Falkland Islands"),
            new SelectListItem(value: "FM", text: "Micronesia"),
            new SelectListItem(value: "FO", text: "Faroe Islands"),
            new SelectListItem(value: "NI", text: "Nicaragua"),
            new SelectListItem(value: "NL", text: "Netherlands"),
            new SelectListItem(value: "NO", text: "Norway"),
            new SelectListItem(value: "NA", text: "Namibia"),
            new SelectListItem(value: "VU", text: "Vanuatu"),
            new SelectListItem(value: "NC", text: "New Caledonia"),
            new SelectListItem(value: "NE", text: "Niger"),
            new SelectListItem(value: "NF", text: "Norfolk Island"),
            new SelectListItem(value: "NG", text: "Nigeria"),
            new SelectListItem(value: "NZ", text: "New Zealand"),
            new SelectListItem(value: "NP", text: "Nepal"),
            new SelectListItem(value: "NR", text: "Nauru"),
            new SelectListItem(value: "NU", text: "Niue"),
            new SelectListItem(value: "CK", text: "Cook Islands"),
            new SelectListItem(value: "XK", text: "Kosovo"),
            new SelectListItem(value: "CI", text: "Ivory Coast"),
            new SelectListItem(value: "CH", text: "Switzerland"),
            new SelectListItem(value: "CO", text: "Colombia"),
            new SelectListItem(value: "CN", text: "China"),
            new SelectListItem(value: "CM", text: "Cameroon"),
            new SelectListItem(value: "CL", text: "Chile"),
            new SelectListItem(value: "CC", text: "Cocos Islands"),
            new SelectListItem(value: "CA", text: "Canada"),
            new SelectListItem(value: "CG", text: "Republic of the Congo"),
            new SelectListItem(value: "CF", text: "Central African Republic"),
            new SelectListItem(value: "CD", text: "Democratic Republic of the Congo"),
            new SelectListItem(value: "CZ", text: "Czech Republic"),
            new SelectListItem(value: "CY", text: "Cyprus"),
            new SelectListItem(value: "CX", text: "Christmas Island"),
            new SelectListItem(value: "CR", text: "Costa Rica"),
            new SelectListItem(value: "CW", text: "Curacao"),
            new SelectListItem(value: "CV", text: "Cape Verde"),
            new SelectListItem(value: "CU", text: "Cuba"),
            new SelectListItem(value: "SZ", text: "Swaziland"),
            new SelectListItem(value: "SY", text: "Syria"),
            new SelectListItem(value: "SX", text: "Sint Maarten"),
            new SelectListItem(value: "KG", text: "Kyrgyzstan"),
            new SelectListItem(value: "KE", text: "Kenya"),
            new SelectListItem(value: "SS", text: "South Sudan"),
            new SelectListItem(value: "SR", text: "Suriname"),
            new SelectListItem(value: "KI", text: "Kiribati"),
            new SelectListItem(value: "KH", text: "Cambodia"),
            new SelectListItem(value: "KN", text: "Saint Kitts and Nevis"),
            new SelectListItem(value: "KM", text: "Comoros"),
            new SelectListItem(value: "ST", text: "Sao Tome and Principe"),
            new SelectListItem(value: "SK", text: "Slovakia"),
            new SelectListItem(value: "KR", text: "South Korea"),
            new SelectListItem(value: "SI", text: "Slovenia"),
            new SelectListItem(value: "KP", text: "North Korea"),
            new SelectListItem(value: "KW", text: "Kuwait"),
            new SelectListItem(value: "SN", text: "Senegal"),
            new SelectListItem(value: "SM", text: "San Marino"),
            new SelectListItem(value: "SL", text: "Sierra Leone"),
            new SelectListItem(value: "SC", text: "Seychelles"),
            new SelectListItem(value: "KZ", text: "Kazakhstan"),
            new SelectListItem(value: "KY", text: "Cayman Islands"),
            new SelectListItem(value: "SG", text: "Singapore"),
            new SelectListItem(value: "SE", text: "Sweden"),
            new SelectListItem(value: "SD", text: "Sudan"),
            new SelectListItem(value: "DO", text: "Dominican Republic"),
            new SelectListItem(value: "DM", text: "Dominica"),
            new SelectListItem(value: "DJ", text: "Djibouti"),
            new SelectListItem(value: "DK", text: "Denmark"),
            new SelectListItem(value: "VG", text: "British Virgin Islands"),
            new SelectListItem(value: "DE", text: "Germany"),
            new SelectListItem(value: "YE", text: "Yemen"),
            new SelectListItem(value: "DZ", text: "Algeria"),
            new SelectListItem(value: "US", text: "United States"),
            new SelectListItem(value: "UY", text: "Uruguay"),
            new SelectListItem(value: "YT", text: "Mayotte"),
            new SelectListItem(value: "UM", text: "United States Minor Outlying Islands"),
            new SelectListItem(value: "LB", text: "Lebanon"),
            new SelectListItem(value: "LC", text: "Saint Lucia"),
            new SelectListItem(value: "LA", text: "Laos"),
            new SelectListItem(value: "TV", text: "Tuvalu"),
            new SelectListItem(value: "TW", text: "Taiwan"),
            new SelectListItem(value: "TT", text: "Trinidad and Tobago"),
            new SelectListItem(value: "TR", text: "Turkey"),
            new SelectListItem(value: "LK", text: "Sri Lanka"),
            new SelectListItem(value: "LI", text: "Liechtenstein"),
            new SelectListItem(value: "LV", text: "Latvia"),
            new SelectListItem(value: "TO", text: "Tonga"),
            new SelectListItem(value: "LT", text: "Lithuania"),
            new SelectListItem(value: "LU", text: "Luxembourg"),
            new SelectListItem(value: "LR", text: "Liberia"),
            new SelectListItem(value: "LS", text: "Lesotho"),
            new SelectListItem(value: "TH", text: "Thailand"),
            new SelectListItem(value: "TF", text: "French Southern Territories"),
            new SelectListItem(value: "TG", text: "Togo"),
            new SelectListItem(value: "TD", text: "Chad"),
            new SelectListItem(value: "TC", text: "Turks and Caicos Islands"),
            new SelectListItem(value: "LY", text: "Libya"),
            new SelectListItem(value: "VA", text: "Vatican"),
            new SelectListItem(value: "VC", text: "Saint Vincent and the Grenadines"),
            new SelectListItem(value: "AE", text: "United Arab Emirates"),
            new SelectListItem(value: "AD", text: "Andorra"),
            new SelectListItem(value: "AG", text: "Antigua and Barbuda"),
            new SelectListItem(value: "AF", text: "Afghanistan"),
            new SelectListItem(value: "AI", text: "Anguilla"),
            new SelectListItem(value: "VI", text: "U.S. Virgin Islands"),
            new SelectListItem(value: "IS", text: "Iceland"),
            new SelectListItem(value: "IR", text: "Iran"),
            new SelectListItem(value: "AM", text: "Armenia"),
            new SelectListItem(value: "AL", text: "Albania"),
            new SelectListItem(value: "AO", text: "Angola"),
            new SelectListItem(value: "AQ", text: "Antarctica"),
            new SelectListItem(value: "AS", text: "American Samoa"),
            new SelectListItem(value: "AR", text: "Argentina"),
            new SelectListItem(value: "AU", text: "Australia"),
            new SelectListItem(value: "AT", text: "Austria"),
            new SelectListItem(value: "AW", text: "Aruba"),
            new SelectListItem(value: "IN", text: "India"),
            new SelectListItem(value: "AX", text: "Aland Islands"),
            new SelectListItem(value: "AZ", text: "Azerbaijan"),
            new SelectListItem(value: "IE", text: "Ireland"),
            new SelectListItem(value: "ID", text: "Indonesia"),
            new SelectListItem(value: "UA", text: "Ukraine"),
            new SelectListItem(value: "QA", text: "Qatar"),
            new SelectListItem(value: "MZ", text: "Mozambique")
        };
    }
}
